# General Properties
java_version=25
minecraft_version=26.1.2
compatible_mc_versions=["26.1.2"]

# Fabric-specific Properties
fabric_loader=0.19.1
fabric_api_version=0.145.4+26.1.2
modmenu_enabled=true
modmenu_version=18.0.0-alpha.8

# Selected loaders
builds_for=fabric
