# General Properties
java_version=21
minecraft_version=26.1.1
compatible_mc_versions=["26.1.1"]

# Fabric-specific Properties
fabric_loader=0.19.1
fabric_api_version=0.145.4+26.1.2
modmenu_enabled=false

# Forge-specific Properties
forge_loader=63.0.2

# Selected loaders
builds_for=fabric,forge
